import { BlogPost } from './types';

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Need To Find Hidden Water Leaks In Your Home? 5 Solutions',
    excerpt: 'Discovering hidden water leaks can save you from unnecessary expenses and water damage.',
    content: [
      'Discovering hidden water leaks in your home can save you from unnecessary expenses and water damage. But how do you locate those sneaky leaks? We\'ve compiled five foolproof solutions that can help you spot hidden water leaks before they wreak havoc on your home.',
      'Hidden water leaks might seem minor at first, but they can lead to significant issues if left unchecked. Here\'s why you should take action:',
      'Pay close attention to your water bill',
      'If your water bill suddenly skyrockets without any changes in usage, a hidden leak could be the culprit.',
      'Review your past bills. Consistent increases over time often indicate a leak',
      'Check your water meter',
      'Your water meter is a reliable tool for detecting leaks.',
      'A slow but steady increase in the meter reading suggests a hidden issue.',
      'Look over your water usage',
      'For an average family of four, usage above 12,000 gallons per month during cooler months may signal a leak. Spotting spikes in your water usage report can guide you to potential problems.',
      'Try the toilet dye test',
      'As per the data, a leaky toilet can waste up to 200 gallons of water daily. Here\'s how to check for leaks:',
      'Dump a few drops of food coloring into your toilet tank.',
      'Wait for 10 minutes without flushing.',
      'If the water in the bowl changes its color then there is a water leak.',
      'Check if your outdoor faucet is leaking',
      'Leaks aren\'t confined to the indoors. Outdoor faucets are another potential source. Wet patches near the faucet and rust or corrosion on the spout indicate water leakage. A hose bib gauge can help measure the flow and pinpoint leaks.',
      'Contacting PRNV Services will help you in providing professional water leak repair services for your home. Our trained plumber professionals are experts in finding these hidden water leaks and will fix them immediately. With PRNV Services\' affordable plumbing services, one can stop the water leaks in the home today.'
    ],
    category: 'PLUMBING SERVICES',
    date: 'Dec 30,2024',
    image: 'https://images.pexels.com/photos/8090081/pexels-photo-8090081.jpeg?auto=compress&cs=tinysrgb&w=400',
    heroImage: 'https://images.pexels.com/photos/5691659/pexels-photo-5691659.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['WATER LEAKS', 'PLUMBING SERVICES IN HYDERABAD', 'HOME MAINTENANCE']
  },
  {
    id: '2',
    title: '12 Essential Washing Machine Maintenance Tips',
    excerpt: 'Keep your washing machine running efficiently with these professional maintenance tips.',
    content: [
      'Your washing machine is one of the most essential appliances in your home, working tirelessly to keep your clothes clean and fresh. However, like any hardworking machine, it requires regular maintenance to function at its best.',
      'Regular maintenance not only extends the life of your washing machine but also ensures it operates efficiently, saving you money on energy bills and costly repairs.',
      'Clean the drum regularly',
      'Run an empty hot water cycle with white vinegar or baking soda monthly to remove buildup and odors.',
      'Check and clean the filter',
      'Most modern washing machines have a filter that catches lint, coins, and small items. Clean it every few months.',
      'Inspect the door seal',
      'Wipe down the rubber door seal after each use to prevent mold and mildew buildup.',
      'Use the right amount of detergent',
      'Too much detergent can cause excessive suds and leave residue on clothes and in the machine.',
      'Balance your loads',
      'Overloading can strain the motor and cause excessive vibration, while underloading wastes water and energy.',
      'Leave the door open after use',
      'This allows air circulation and helps prevent moisture buildup that can lead to odors.',
      'Check hoses regularly',
      'Inspect supply hoses for cracks, bulges, or leaks every six months and replace them every five years.',
      'Level your machine',
      'An unlevel washing machine can cause excessive vibration and premature wear.',
      'Clean the detergent dispenser',
      'Remove and wash the detergent drawer monthly to prevent buildup.',
      'Use appropriate water temperature',
      'Hot water isn\'t always necessary and can damage certain fabrics while wasting energy.',
      'Regular professional servicing',
      'Schedule annual maintenance with PRNV Services to ensure optimal performance.',
      'Keep the area clean',
      'Maintain a clean laundry area to prevent dust and debris from affecting your machine\'s operation.'
    ],
    category: 'APPLIANCE MAINTENANCE',
    date: 'Dec 28,2024',
    image: 'https://images.pexels.com/photos/4239091/pexels-photo-4239091.jpeg?auto=compress&cs=tinysrgb&w=400',
    heroImage: 'https://images.pexels.com/photos/4239091/pexels-photo-4239091.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['WASHING MACHINE', 'APPLIANCE CARE', 'HOME MAINTENANCE']
  },
  {
    id: '3',
    title: '10 Electrical Tips for Brand-New House Owners',
    excerpt: 'Essential electrical safety and maintenance tips every new homeowner should know.',
    content: [
      'Congratulations on your new home! As a new homeowner, understanding your home\'s electrical system is crucial for safety and efficiency. Here are ten essential electrical tips to help you get started.',
      'Electrical safety should be every homeowner\'s top priority. These tips will help you maintain a safe and efficient electrical system.',
      'Locate your main electrical panel',
      'Know where your circuit breaker panel is located and ensure it\'s easily accessible. Label each breaker clearly.',
      'Test GFCI outlets monthly',
      'Ground Fault Circuit Interrupter outlets in bathrooms, kitchens, and outdoor areas should be tested regularly.',
      'Don\'t overload circuits',
      'Avoid plugging too many devices into a single outlet or circuit to prevent overheating.',
      'Replace old outlets and switches',
      'Upgrade old two-prong outlets to three-prong GFCI outlets for better safety.',
      'Install surge protectors',
      'Protect your valuable electronics with quality surge protectors throughout your home.',
      'Check for aluminum wiring',
      'If your home was built between 1965-1973, it may have aluminum wiring that requires special attention.',
      'Ensure proper grounding',
      'All electrical systems should be properly grounded for safety.',
      'Schedule an electrical inspection',
      'Have a professional electrician inspect your home\'s electrical system annually.',
      'Know the warning signs',
      'Flickering lights, burning smells, or warm outlets are signs that require immediate attention.',
      'Plan for future needs',
      'Consider your electrical needs for home offices, electric vehicles, and smart home devices.',
      'At PRNV Services, our certified electricians provide comprehensive electrical inspections and repairs to ensure your home is safe and up to code. Contact us for professional electrical services.'
    ],
    category: 'ELECTRICAL SERVICES',
    date: 'Dec 26,2024',
    image: 'https://images.pexels.com/photos/257736/pexels-photo-257736.jpeg?auto=compress&cs=tinysrgb&w=400',
    heroImage: 'https://images.pexels.com/photos/257736/pexels-photo-257736.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['ELECTRICAL SAFETY', 'NEW HOMEOWNERS', 'HOME INSPECTION']
  }
];